image: python:3.7-alpine
pages:
  stage: deploy
  script:
    - mkdir .public
    - pip install -r requirements_dev.txt
    - sphinx-build -b html docs public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
